CC=g++
KTT_PATH=~/Desktop/parametrisering/KTT/source
KTT_LIBRARY=~/Desktop/parametrisering/KTT/build/x86_64_Release/

default:
	@$(CC) sort.cpp -o sort -I $(KTT_PATH) -L $(KTT_LIBRARY) -lktt

clean:
	@$(RM) sort
